--------------------------------------------------------
--  File created - lunes-agosto-26-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CATEGORIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."CATEGORIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CONTACTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."CONTACTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_FACTURA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."DETALLE_FACTURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."ESTADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FACTURA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."FACTURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JUEGO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."JUEGO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 34 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."ROL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_LENGUAJES"."USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER, 
	"DESCRIPCION" VARCHAR2(255 CHAR), 
	"RUTA_IMAGEN" VARCHAR2(255 CHAR), 
	"ESTADO" NUMBER(1,0), 
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"ACCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table CONTACTO
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."CONTACTO" 
   (	"ID_CONTACTO" NUMBER, 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"APELLIDO" VARCHAR2(255 CHAR), 
	"NUMERO" NUMBER, 
	"MENSAJE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" 
   (	"ID_DETALLE_FACTURA" NUMBER, 
	"ID_FACTURA" NUMBER, 
	"ID_JUEGO" NUMBER, 
	"PRECIO" NUMBER, 
	"CANTIDAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table ERRORES_AUDIT
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."ERRORES_AUDIT" 
   (	"USUARIO" VARCHAR2(50 BYTE), 
	"ORIGEN" VARCHAR2(50 BYTE), 
	"FECHA" DATE, 
	"VERROR" VARCHAR2(600 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."ESTADO" 
   (	"ID_ESTADO" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"ESTADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."FACTURA" 
   (	"ID_FACTURA" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table JUEGO
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."JUEGO" 
   (	"ID_JUEGO" NUMBER, 
	"IMAGEN" VARCHAR2(255 CHAR), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"EMPRESA" VARCHAR2(255 CHAR), 
	"PRECIO" NUMBER, 
	"EXISTENCIAS" NUMBER, 
	"ESTADO" NUMBER(1,0), 
	"ID_CATEGORIA" NUMBER, 
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"ACCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."ROL" 
   (	"ID_ROL" NUMBER, 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "ADMIN_LENGUAJES"."USUARIO" 
   (	"ID_USUARIO" NUMBER, 
	"USERNAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"APELLIDOS" VARCHAR2(255 CHAR), 
	"CORREO" VARCHAR2(255 CHAR), 
	"TELEFONO" VARCHAR2(255 CHAR), 
	"ESTADO" NUMBER(1,0), 
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FECHA_MODIFICACION" TIMESTAMP (6), 
	"CREADO_POR" VARCHAR2(30 BYTE), 
	"MODIFICADO_POR" VARCHAR2(30 BYTE), 
	"ACCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
REM INSERTING into ADMIN_LENGUAJES.CATEGORIA
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (25,'Musical','https://i.scdn.co/image/ab67616d0000b273bcd93b95683ca20bfbe2805a',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (1,'Accion','https://wallpaperaccess.com/full/5485133.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (2,'Aventura','https://miracomosehace.com/wp-content/uploads/2021/06/rayman-adventures.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (3,'Deporte','https://www.clarin.com/img/2022/12/06/pUy2oLemU_1256x620__1.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (4,'Estrategia','https://media.vandal.net/m/1-2019/2019181558171_1.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (5,'RPG','https://www.mundodeportivo.com/alfabeta/hero/2020/09/juegos-rpg-pc-2.jpg?width=1200',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (6,'Puzzle','https://i.blogs.es/50cfcf/juegos-de-puzzles/1366_2000.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.CATEGORIA (ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (7,'ajedrez','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/ChessSet.jpg/800px-ChessSet.jpg',1,to_timestamp('18-AUG-24 07.09.13.307000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
REM INSERTING into ADMIN_LENGUAJES.CONTACTO
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (8,'Diana','Larcia',87459698,'Excelente atention al cliente');
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (5,'Roberto','Batista',87459632,'Tengo problemas con un juego que les compre ayer..........');
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (6,'Julia','Mata',21457835,'Necesito cotizar algunos juegos, me podrian contactar?');
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (7,'Vale','Amador',60124587,'Tienen Halo?');
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (1,'Hector','Hernandez',72063542,'Tienen COD?');
Insert into ADMIN_LENGUAJES.CONTACTO (ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE) values (2,'Ana','Vargas',88114617,'Quiero Elder Ring, please');
REM INSERTING into ADMIN_LENGUAJES.DETALLE_FACTURA
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.DETALLE_FACTURA (ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) values (11,6,26,60,1);
Insert into ADMIN_LENGUAJES.DETALLE_FACTURA (ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) values (12,7,26,60,1);
Insert into ADMIN_LENGUAJES.DETALLE_FACTURA (ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) values (5,1,16,59.99,1);
Insert into ADMIN_LENGUAJES.DETALLE_FACTURA (ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) values (6,1,18,80.99,1);
Insert into ADMIN_LENGUAJES.DETALLE_FACTURA (ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) values (9,4,26,60,1);
REM INSERTING into ADMIN_LENGUAJES.ERRORES_AUDIT
SET DEFINE OFF;
REM INSERTING into ADMIN_LENGUAJES.ESTADO
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.ESTADO (ID_ESTADO,DESCRIPCION,ESTADO) values (1,'Activo',1);
Insert into ADMIN_LENGUAJES.ESTADO (ID_ESTADO,DESCRIPCION,ESTADO) values (2,'Inactivo',0);
REM INSERTING into ADMIN_LENGUAJES.FACTURA
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL) values (6,2,to_timestamp('05-AUG-24 10.10.24.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
Insert into ADMIN_LENGUAJES.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL) values (7,2,to_timestamp('05-AUG-24 10.31.45.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
Insert into ADMIN_LENGUAJES.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL) values (1,2,to_timestamp('27-JUL-24 12.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),140.98);
Insert into ADMIN_LENGUAJES.FACTURA (ID_FACTURA,ID_USUARIO,FECHA,TOTAL) values (4,1,to_timestamp('03-AUG-24 12.35.01.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),60);
REM INSERTING into ADMIN_LENGUAJES.JUEGO
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (26,'https://image.api.playstation.com/cdn/UP0002/CUSA07402_00/03ZtrPdjasIxzi8QrzOb2zCIHLMydFbh.png','Crash','Activision',55.89,5,1,2,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('18-AUG-24 08.59.26.461000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,'ADMIN_LENGUAJES','ACTUALIZAR');
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (32,'https://media.vandal.net/i/1440x1080/5-2023/20235223395250_1.jpg','The Legend of Zelda: Breath of the Wild','Nintendo',59,3,1,2,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (10,'https://metodologic.net/wp-content/uploads/2017/11/Mario_Odyssey_portada.jpg','Super Mario Odyssey','Nintendo',59.99,4,1,2,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (11,'https://media.vandal.net/i/1440x1080/5-2023/20235223395250_1.jpg','The Legend of Zelda: Breath of the Wild','Nintendo',59.99,4,1,2,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (12,'https://e1.pngegg.com/pngimages/517/222/png-clipart-grand-theft-auto-v-game-icon-gta-5-7-gta-v-game-cover-thumbnail.png','Grand Theft Auto V','Rockstar Games',29.99,2,1,1,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (13,'https://futbolete.com/apuestas/wp-content/uploads/2021/09/FIFA-22-Esta-es-la-valoracion-de-Kylian-Mbappe-portada-del-juego-1200x900.jpg','FIFA 22','EA Sports',49.99,7,1,3,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (14,'https://img.zonared.com/images/noticias/portada/47000/47269-h2.jpg','Minecraft','Mojang Studios',29.99,2,1,2,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (15,'https://media.vandal.net/i/640x360/12-2022/202212111754215_1.jpg','The Witcher 3: Wild Hunt','CD Projekt',39.99,4,1,4,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (16,'https://i.blogs.es/88d2ec/cod_mw/450_1000.webp','Call of Duty: Modern Warfare','Activision',59.99,8,1,1,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (17,'https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_AmongUs_image1600w.jpg','Among Us','InnerSloth',4.99,5,1,5,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.JUEGO (ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (18,'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2023/08/29/16933298615638.jpg','League of Legends','Riot Games',80.99,9,1,4,to_timestamp('18-AUG-24 08.57.09.494000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
REM INSERTING into ADMIN_LENGUAJES.ROL
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.ROL (ID_ROL,NOMBRE,ID_USUARIO) values (4,'ROLE_USER',1);
Insert into ADMIN_LENGUAJES.ROL (ID_ROL,NOMBRE,ID_USUARIO) values (1,'ROLE_ADMIN',1);
Insert into ADMIN_LENGUAJES.ROL (ID_ROL,NOMBRE,ID_USUARIO) values (2,'ROLE_USER',2);
Insert into ADMIN_LENGUAJES.ROL (ID_ROL,NOMBRE,ID_USUARIO) values (3,'ROLE_USER',3);
REM INSERTING into ADMIN_LENGUAJES.USUARIO
SET DEFINE OFF;
Insert into ADMIN_LENGUAJES.USUARIO (ID_USUARIO,USERNAME,PASSWORD,NOMBRE,APELLIDOS,CORREO,TELEFONO,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (1,'hhernan','$2a$12$BBmQIiQQ6KgfGj/4Pf1MmO6KIWmE/7mDWgYaUQu.i88H4gt1F7C9e','Hector','Hernandez','hhernan93vargas@gmail.com','72063542',1,to_timestamp('18-AUG-24 08.58.38.744000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.USUARIO (ID_USUARIO,USERNAME,PASSWORD,NOMBRE,APELLIDOS,CORREO,TELEFONO,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (2,'ann','$2a$12$JEItlF5yxhVvkQ/qvDqqiuVoOjc5uU1boLAVeg9eQT0irRkQA9QJG','Ana','Vargas','annv@gmail.com','88114617',1,to_timestamp('18-AUG-24 08.58.38.744000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
Insert into ADMIN_LENGUAJES.USUARIO (ID_USUARIO,USERNAME,PASSWORD,NOMBRE,APELLIDOS,CORREO,TELEFONO,ESTADO,FECHA_CREACION,FECHA_MODIFICACION,CREADO_POR,MODIFICADO_POR,ACCION) values (3,'hcin','$2a$10$ZM3FutOTWyUqIb7qKX6Uj.BYmjiC9NAWmElOtQ1qCYkHNhCqSFYMO','Cindy','Hernandez','cin@gmail.com','88888888',1,to_timestamp('18-AUG-24 08.58.38.744000000 PM','DD-MON-RR HH.MI.SSXFF AM'),null,null,null,null);
--------------------------------------------------------
--  DDL for Index CATEG_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."CATEG_ID_IDX" ON "ADMIN_LENGUAJES"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index CONT_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."CONT_ID_IDX" ON "ADMIN_LENGUAJES"."CONTACTO" ("ID_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index DETALLE_FACTURA_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."DETALLE_FACTURA_ID_IDX" ON "ADMIN_LENGUAJES"."DETALLE_FACTURA" ("ID_DETALLE_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index EST_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."EST_ID_IDX" ON "ADMIN_LENGUAJES"."ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index FACT_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."FACT_ID_IDX" ON "ADMIN_LENGUAJES"."FACTURA" ("ID_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index JUEGO_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."JUEGO_ID_IDX" ON "ADMIN_LENGUAJES"."JUEGO" ("ID_JUEGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index ROL_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."ROL_ID_IDX" ON "ADMIN_LENGUAJES"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index USU_ID_IDX
--------------------------------------------------------

  CREATE INDEX "ADMIN_LENGUAJES"."USU_ID_IDX" ON "ADMIN_LENGUAJES"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Index U_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN_LENGUAJES"."U_ESTADO" ON "ADMIN_LENGUAJES"."ESTADO" ("ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" ;
--------------------------------------------------------
--  DDL for Trigger CATEGORIA_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."CATEGORIA_BEFORE_INSERT" 
    BEFORE INSERT ON CATEGORIA
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CATEGORIA IS NULL THEN
            SELECT CATEGORIA_SEQ.NEXTVAL
            INTO :NEW.ID_CATEGORIA
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."CATEGORIA_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIA_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."CATEGORIA_TRG" 
BEFORE INSERT OR UPDATE ON CATEGORIA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION:='INSERTAR';
    ELSIF UPDATING THEN

        :NEW.FECHA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION:='ACTUALIZAR';
    END IF;
END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."CATEGORIA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTACTO_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."CONTACTO_BEFORE_INSERT" 
    BEFORE INSERT ON CONTACTO
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_CONTACTO IS NULL THEN
            SELECT CONTACTO_SEQ.NEXTVAL
            INTO :NEW.ID_CONTACTO
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."CONTACTO_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_FACTURA_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."DETALLE_FACTURA_BEFORE_INSERT" 
    BEFORE INSERT ON DETALLE_FACTURA
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_DETALLE_FACTURA IS NULL THEN
            SELECT DETALLE_FACTURA_SEQ.NEXTVAL
            INTO :NEW.ID_DETALLE_FACTURA
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."DETALLE_FACTURA_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."ESTADO_BEFORE_INSERT" 
    BEFORE INSERT ON ESTADO
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ESTADO IS NULL THEN
            SELECT ESTADO_SEQ.NEXTVAL
            INTO :NEW.ID_ESTADO
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."ESTADO_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FACTURA_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."FACTURA_BEFORE_INSERT" 
    BEFORE INSERT ON FACTURA
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_FACTURA IS NULL THEN
            SELECT FACTURA_SEQ.NEXTVAL
            INTO :NEW.ID_FACTURA
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."FACTURA_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JUEGO_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."JUEGO_BEFORE_INSERT" 
    BEFORE INSERT ON JUEGO
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_JUEGO IS NULL THEN
            SELECT JUEGO_SEQ.NEXTVAL
            INTO :NEW.ID_JUEGO
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."JUEGO_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JUEGO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."JUEGO_TRG" 
BEFORE INSERT OR UPDATE ON JUEGO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION:='INSERTAR';
    ELSIF UPDATING THEN

        :NEW.FECHA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION:='ACTUALIZAR';
    END IF;
END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."JUEGO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROL_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."ROL_BEFORE_INSERT" 
    BEFORE INSERT ON ROL
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_ROL IS NULL THEN
            SELECT ROL_SEQ.NEXTVAL
            INTO :NEW.ID_ROL
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."ROL_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIO_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."USUARIO_BEFORE_INSERT" 
    BEFORE INSERT ON USUARIO
    FOR EACH ROW
    BEGIN
        IF :NEW.ID_USUARIO IS NULL THEN
            SELECT USUARIO_SEQ.NEXTVAL
            INTO :NEW.ID_USUARIO
            FROM DUAL;
        END IF;
    END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."USUARIO_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN_LENGUAJES"."USUARIO_TRG" 
BEFORE INSERT OR UPDATE ON USUARIO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.FECHA_CREACION := CURRENT_TIMESTAMP;
        :NEW.CREADO_POR := USER;
        :NEW.ACCION:='INSERTAR';
    ELSIF UPDATING THEN

        :NEW.FECHA_MODIFICACION := CURRENT_TIMESTAMP;
        :NEW.MODIFICADO_POR := USER;
        :NEW.ACCION:='ACTUALIZAR';
    END IF;
END;
/
ALTER TRIGGER "ADMIN_LENGUAJES"."USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADD_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_CATEGORIA" (DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS

BEGIN
    INSERT INTO CATEGORIA (DESCRIPCION,RUTA_IMAGEN,ESTADO) VALUES (DESCRIP,IMG,ACT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_CONTACTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_CONTACTO" (NOMBRE IN VARCHAR2,APELLIDO IN VARCHAR2,NUMERO IN NUMBER,MENSAJE IN VARCHAR2 ) AS

BEGIN
    INSERT INTO CONTACTO (NOMBRE,APELLIDO,NUMERO,MENSAJE) VALUES (NOMBRE,APELLIDO,NUMERO,MENSAJE);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_DETALLE_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_DETALLE_FACTURA" (IDFACT IN NUMBER,IDJUEGO IN NUMBER,PRECIO IN NUMBER,CANTIDAD IN NUMBER ) AS
BEGIN
    INSERT INTO DETALLE_FACTURA (ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) VALUES (IDFACT,IDJUEGO,PRECIO,CANTIDAD);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_FACTURA" (USID IN NUMBER,FECHA IN DATE,TOTAL IN NUMBER) AS

BEGIN
    INSERT INTO FACTURA (ID_USUARIO,FECHA,TOTAL) VALUES (USID,FECHA,TOTAL);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_JUEGO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_JUEGO" (IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS 
BEGIN
    INSERT INTO JUEGO (IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA) VALUES (IMG,NOM,EMP,PREC,EXI,EST,ID_CAT);
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_ROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_ROL" (RNAME IN VARCHAR2,IDUSER IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    INSERT INTO ROL (NOMBRE,ID_USUARIO) VALUES (RNAME,IDUSER);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT VALUES (USER,'ADD_ROL',SYSDATE, VCOD || ' - '|| VMES );

END;

/
--------------------------------------------------------
--  DDL for Procedure ADD_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."ADD_USUARIO" (UNAME IN VARCHAR2,PASS IN VARCHAR2,UNOM IN VARCHAR2,APELL IN VARCHAR2,CORRE IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
BEGIN
    INSERT INTO USUARIO (USERNAME, PASSWORD,NOMBRE, APELLIDOS,CORREO, TELEFONO,ESTADO) VALUES (UNAME,PASS,UNOM, APELL,CORRE, TEL,EST);
EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT VALUES (USER,'ADD_ROL',SYSDATE, VCOD || ' - '|| VMES );
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."DELETE_CATEGORIA" (CID IN NUMBER ) AS
BEGIN
    DELETE FROM CATEGORIA WHERE ID_CATEGORIA=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_CONTACTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."DELETE_CONTACTO" (CID IN NUMBER ) AS
BEGIN
    DELETE FROM CONTACTO WHERE ID_CONTACTO=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_JUEGO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."DELETE_JUEGO" (JID IN NUMBER ) AS
BEGIN
    DELETE FROM JUEGO WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure DELETE_ROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."DELETE_ROL" (IDU IN NUMBER ) AS
BEGIN
    DELETE FROM ROL WHERE ID_USUARIO=IDU;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END; 

/
--------------------------------------------------------
--  DDL for Procedure DELETE_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."DELETE_USUARIO" (USEID IN NUMBER ) AS
BEGIN
    PACKAGE_ROL.DELETE_ROL(USEID);
    DELETE FROM USUARIO WHERE ID_USUARIO=USEID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_CATEGORIA" (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO FROM CATEGORIA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_CATEGORIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_CATEGORIAS" (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA, DESCRIPCION FROM CATEGORIA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_CATEGORIA_DESC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_CATEGORIA_DESC" (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION FROM CATEGORIA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_CONTACTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_CONTACTO" (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE FROM CONTACTO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_DETALLES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_DETALLES" (DATOS OUT SYS_REFCURSOR)
AS  
    VSQL VARCHAR2(1024);
BEGIN
    VSQL := 'SELECT ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD
             FROM DETALLE_FACTURA';
    OPEN DATOS FOR VSQL;
EXCEPTION    
   WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('***   ERROR DE FILAS MULTIPLES  ****');       
 WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('***   NO HAY DATOS  ****');      
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_FACTURAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_FACTURAS" (DATOS OUT SYS_REFCURSOR)
AS  
    VSQL VARCHAR2(1024);
BEGIN
    VSQL := 'SELECT ID_FACTURA, ID_USUARIO,FECHA,TOTAL
             FROM FACTURA';
    OPEN DATOS FOR VSQL;
EXCEPTION    
   WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('***   ERROR DE FILAS MULTIPLES  ****');       
 WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('***   NO HAY DATOS  ****');      
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_FACTURA_ID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_FACTURA_ID" (FECH IN DATE,DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_FACTURA FROM FACTURA WHERE FECHA=FECH;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_JUEGOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_JUEGOS" (DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_JUEGOSBYCATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_JUEGOSBYCATEGORIA" (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_ONE_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_ONE_CATEGORIA" (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO FROM CATEGORIA WHERE ID_CATEGORIA=CID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_ONE_JUEGO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_ONE_JUEGO" (JID IN NUMBER,DATOS OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_JUEGO=JID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_ROLES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_ROLES" (UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT NOMBRE FROM ROL
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_USERNAMEANDPASSWORD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_USERNAMEANDPASSWORD" (UNAME IN VARCHAR2, PASS IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
   WHERE USERNAME = UNAME and PASSWORD = PASS;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_USERNAMEORCORREO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_USERNAMEORCORREO" (UNAME IN VARCHAR2, CORRE IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
   WHERE USERNAME = UNAME OR CORREO = CORRE;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_USUARIOBYID
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_USUARIOBYID" (UID IN NUMBER, DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
   WHERE ID_USUARIO = UID;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_USUARIOBYUSERNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_USUARIOBYUSERNAME" (UNAME IN VARCHAR2, DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
   WHERE USERNAME = UNAME;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure GET_USUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."GET_USUARIOS" (DATOS OUT SYS_REFCURSOR)
 AS
 BEGIN
   OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
 END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."UPDATE_CATEGORIA" (CID IN NUMBER,DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
BEGIN
    UPDATE CATEGORIA SET DESCRIPCION = DESCRIP ,RUTA_IMAGEN = IMG,ESTADO = ACT WHERE ID_CATEGORIA=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."UPDATE_FACTURA" (FID IN NUMBER,TOTL IN NUMBER) AS

BEGIN
    UPDATE FACTURA SET TOTAL=TOTL WHERE ID_FACTURA=FID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_JUEGO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."UPDATE_JUEGO" (JID IN NUMBER,IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS
BEGIN
    UPDATE JUEGO SET IMAGEN = IMG ,NOMBRE = NOM,EMPRESA = EMP,PRECIO = PREC ,EXISTENCIAS = EXI ,ESTADO = EST,ID_CATEGORIA=ID_CAT  WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN_LENGUAJES"."UPDATE_USUARIO" (USERID IN NUMBER,USNAM IN VARCHAR2,CONTRAS IN VARCHAR2,NOMBR IN VARCHAR2,APELLI IN VARCHAR2,MAIL IN VARCHAR2,PHONE IN VARCHAR2,ACTV IN NUMBER) AS
BEGIN
    UPDATE USUARIO SET USERNAME=USNAM, PASSWORD=CONTRAS,NOMBRE=NOMBR, APELLIDOS=APELLI,CORREO=MAIL, TELEFONO=PHONE,ESTADO=ACTV WHERE ID_USUARIO=USERID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_CATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_CATEGORIA" AS
    PROCEDURE ADD_CATEGORIA (DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER );
    PROCEDURE GET_CATEGORIA (DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_ONE_CATEGORIA (CID IN NUMBER,DATOS OUT SYS_REFCURSOR);
    PROCEDURE DELETE_CATEGORIA (CID IN NUMBER );
    PROCEDURE UPDATE_CATEGORIA (CID IN NUMBER,DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER );
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_CONTACTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_CONTACTO" AS
    PROCEDURE GET_CONTACTO (DATOS OUT SYS_REFCURSOR);
    PROCEDURE ADD_CONTACTO (NOMBRE IN VARCHAR2,APELLIDO IN VARCHAR2,NUMERO IN NUMBER,MENSAJE IN VARCHAR2);
    PROCEDURE DELETE_CONTACTO (CID IN NUMBER);
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_DETALLE_FACTURA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_DETALLE_FACTURA" AS
    PROCEDURE ADD_DETALLE_FACTURA (IDFACT IN NUMBER,IDJUEGO IN NUMBER,PRECIO IN NUMBER,CANTIDAD IN NUMBER);
    PROCEDURE GET_DETALLES (DATOS OUT SYS_REFCURSOR);
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_FACTURA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_FACTURA" AS
    PROCEDURE ADD_FACTURA (USID IN NUMBER,FECHA IN DATE,TOTAL IN NUMBER);
    PROCEDURE UPDATE_FACTURA (FID IN NUMBER,TOTL IN NUMBER);
    PROCEDURE GET_FACTURA_ID (FECH IN DATE,DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_FACTURAS (DATOS OUT SYS_REFCURSOR);
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_JUEGO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_JUEGO" AS
    PROCEDURE GET_JUEGOS (DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_ONE_JUEGO (JID IN NUMBER,DATOS OUT SYS_REFCURSOR);
    PROCEDURE ADD_JUEGO (IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER);
    PROCEDURE DELETE_JUEGO (JID IN NUMBER);
    PROCEDURE UPDATE_JUEGO (JID IN NUMBER,IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER);
    PROCEDURE GET_CATEGORIAS (DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_JUEGOSBYCATEGORIA (CID IN NUMBER,DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_CATEGORIA_DESC (DATOS OUT SYS_REFCURSOR);
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_ROL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_ROL" AS
    PROCEDURE ADD_ROL (RNAME IN VARCHAR2,IDUSER IN NUMBER);
    PROCEDURE DELETE_ROL (IDU IN NUMBER);
END;

/
--------------------------------------------------------
--  DDL for Package PACKAGE_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "ADMIN_LENGUAJES"."PACKAGE_USUARIO" AS
    PROCEDURE GET_USUARIOS (DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_USUARIOBYID (UID IN NUMBER, DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_USUARIOBYUSERNAME (UNAME IN VARCHAR2, DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_USERNAMEANDPASSWORD(UNAME IN VARCHAR2, PASS IN VARCHAR2, DATOS OUT SYS_REFCURSOR);
    PROCEDURE GET_USERNAMEORCORREO(UNAME IN VARCHAR2, CORRE IN VARCHAR2, DATOS OUT SYS_REFCURSOR);
    PROCEDURE ADD_USUARIO (UNAME IN VARCHAR2,PASS IN VARCHAR2,UNOM IN VARCHAR2,APELL IN VARCHAR2,CORRE IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER);
    PROCEDURE GET_ROLES(UID IN NUMBER, DATOS OUT SYS_REFCURSOR);
    PROCEDURE UPDATE_USUARIO (USERID IN NUMBER,USNAM IN VARCHAR2,CONTRAS IN VARCHAR2,NOMBR IN VARCHAR2,APELLI IN VARCHAR2,MAIL IN VARCHAR2,PHONE IN VARCHAR2,ACTV IN NUMBER);
    PROCEDURE DELETE_USUARIO (USEID IN NUMBER);
    FUNCTION USUARIO_EXISTE (UNAME IN VARCHAR2, CORRE IN VARCHAR2)RETURN NUMBER;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_CATEGORIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_CATEGORIA" AS
    PROCEDURE ADD_CATEGORIA (DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    BEGIN
    INSERT INTO CATEGORIA (DESCRIPCION,RUTA_IMAGEN,ESTADO) VALUES (DESCRIP,IMG,ACT);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE GET_CATEGORIA (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO FROM CATEGORIA;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_ONE_CATEGORIA (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION,RUTA_IMAGEN,ESTADO FROM CATEGORIA WHERE ID_CATEGORIA=CID;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE DELETE_CATEGORIA (CID IN NUMBER ) AS
    BEGIN
    DELETE FROM CATEGORIA WHERE ID_CATEGORIA=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró la categoría con ID para eliminar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE UPDATE_CATEGORIA (CID IN NUMBER,DESCRIP IN VARCHAR2,IMG IN VARCHAR2,ACT IN NUMBER ) AS
    BEGIN
    UPDATE CATEGORIA SET DESCRIPCION = DESCRIP ,RUTA_IMAGEN = IMG,ESTADO = ACT WHERE ID_CATEGORIA=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_CONTACTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_CONTACTO" AS
    PROCEDURE GET_CONTACTO (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_CONTACTO,NOMBRE,APELLIDO,NUMERO,MENSAJE FROM CONTACTO;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE ADD_CONTACTO (NOMBRE IN VARCHAR2,APELLIDO IN VARCHAR2,NUMERO IN NUMBER,MENSAJE IN VARCHAR2 ) AS
    BEGIN
    INSERT INTO CONTACTO (NOMBRE,APELLIDO,NUMERO,MENSAJE) VALUES (NOMBRE,APELLIDO,NUMERO,MENSAJE);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE DELETE_CONTACTO (CID IN NUMBER ) AS
    BEGIN
    DELETE FROM CONTACTO WHERE ID_CONTACTO=CID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró la categoría con ID para eliminar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_DETALLE_FACTURA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_DETALLE_FACTURA" AS
    PROCEDURE ADD_DETALLE_FACTURA (IDFACT IN NUMBER,IDJUEGO IN NUMBER,PRECIO IN NUMBER,CANTIDAD IN NUMBER ) AS
    BEGIN
    INSERT INTO DETALLE_FACTURA (ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD) VALUES (IDFACT,IDJUEGO,PRECIO,CANTIDAD);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE GET_DETALLES (DATOS OUT SYS_REFCURSOR)
    AS  
    VSQL VARCHAR2(1024);
    BEGIN
    VSQL := 'SELECT ID_DETALLE_FACTURA,ID_FACTURA,ID_JUEGO,PRECIO,CANTIDAD
             FROM DETALLE_FACTURA';
    OPEN DATOS FOR VSQL;
    EXCEPTION    
    WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('***   ERROR DE FILAS MULTIPLES  ****');       
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('***   NO HAY DATOS  ****');      
    END;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_FACTURA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_FACTURA" AS
    PROCEDURE ADD_FACTURA (USID IN NUMBER,FECHA IN DATE,TOTAL IN NUMBER) AS
    BEGIN
    INSERT INTO FACTURA (ID_USUARIO,FECHA,TOTAL) VALUES (USID,FECHA,TOTAL);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE UPDATE_FACTURA (FID IN NUMBER,TOTL IN NUMBER) AS
    BEGIN
    UPDATE FACTURA SET TOTAL=TOTL WHERE ID_FACTURA=FID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE GET_FACTURA_ID (FECH IN DATE,DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_FACTURA FROM FACTURA WHERE FECHA=FECH;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_FACTURAS (DATOS OUT SYS_REFCURSOR)
    AS  
    VSQL VARCHAR2(1024);
    BEGIN
    VSQL := 'SELECT ID_FACTURA, ID_USUARIO,FECHA,TOTAL
             FROM FACTURA';
    OPEN DATOS FOR VSQL;
    EXCEPTION    
    WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('***   ERROR DE FILAS MULTIPLES  ****');       
    WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('***   NO HAY DATOS  ****');      
    END;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_JUEGO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_JUEGO" AS
    PROCEDURE GET_JUEGOS (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_ONE_JUEGO (JID IN NUMBER,DATOS OUT SYS_REFCURSOR) AS
    BEGIN
    OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_JUEGO=JID;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE ADD_JUEGO (IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS 
    BEGIN
    INSERT INTO JUEGO (IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA) VALUES (IMG,NOM,EMP,PREC,EXI,EST,ID_CAT);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE DELETE_JUEGO (JID IN NUMBER ) AS
    BEGIN
    DELETE FROM JUEGO WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró la categoría con ID para eliminar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE UPDATE_JUEGO (JID IN NUMBER,IMG IN VARCHAR2,NOM IN VARCHAR2,EMP IN VARCHAR2,PREC IN NUMBER,EXI IN NUMBER,EST IN NUMBER,ID_CAT IN NUMBER ) AS
    BEGIN
    UPDATE JUEGO SET IMAGEN = IMG ,NOMBRE = NOM,EMPRESA = EMP,PRECIO = PREC ,EXISTENCIAS = EXI ,ESTADO = EST,ID_CATEGORIA=ID_CAT  WHERE ID_JUEGO=JID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE GET_CATEGORIAS (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_CATEGORIA, DESCRIPCION FROM CATEGORIA;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_JUEGOSBYCATEGORIA (CID IN NUMBER,DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_JUEGO,IMAGEN,NOMBRE,EMPRESA,PRECIO,EXISTENCIAS,ESTADO,ID_CATEGORIA FROM JUEGO WHERE ID_CATEGORIA=CID;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_CATEGORIA_DESC (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_CATEGORIA,DESCRIPCION FROM CATEGORIA;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_ROL
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_ROL" AS
    PROCEDURE ADD_ROL (RNAME IN VARCHAR2,IDUSER IN NUMBER) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
    BEGIN
    INSERT INTO ROL (NOMBRE,ID_USUARIO) VALUES (RNAME,IDUSER);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT VALUES (USER,'ADD_ROL',SYSDATE, VCOD || ' - '|| VMES );
    END;

    PROCEDURE DELETE_ROL (IDU IN NUMBER ) AS
    BEGIN
    DELETE FROM ROL WHERE ID_USUARIO=IDU;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró el ID para eliminar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END; 
END;

/
--------------------------------------------------------
--  DDL for Package Body PACKAGE_USUARIO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ADMIN_LENGUAJES"."PACKAGE_USUARIO" AS
    PROCEDURE GET_USUARIOS (DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO;
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_USUARIOBYID (UID IN NUMBER, DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
    WHERE ID_USUARIO = UID;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_USUARIOBYUSERNAME (UNAME IN VARCHAR2, DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
    WHERE USERNAME = UNAME;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_USERNAMEANDPASSWORD(UNAME IN VARCHAR2, PASS IN VARCHAR2, DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
    WHERE USERNAME = UNAME and PASSWORD = PASS;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE GET_USERNAMEORCORREO(UNAME IN VARCHAR2, CORRE IN VARCHAR2, DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO
    WHERE USERNAME = UNAME OR CORREO = CORRE;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE ADD_USUARIO (UNAME IN VARCHAR2,PASS IN VARCHAR2,UNOM IN VARCHAR2,APELL IN VARCHAR2,CORRE IN VARCHAR2,TEL IN VARCHAR2,EST IN NUMBER ) AS
    VCOD NUMBER;
    VMES VARCHAR2(500);
    BEGIN
    INSERT INTO USUARIO (USERNAME, PASSWORD,NOMBRE, APELLIDOS,CORREO, TELEFONO,ESTADO) VALUES (UNAME,PASS,UNOM, APELL,CORRE, TEL,EST);
    EXCEPTION
    WHEN VALUE_ERROR THEN
        VMES := SQLERRM;
        VCOD := SQLCODE;
        INSERT INTO ERRORES_AUDIT VALUES (USER,'ADD_ROL',SYSDATE, VCOD || ' - '|| VMES );
    END;

    PROCEDURE DELETE_USUARIO (USEID IN NUMBER ) AS
    BEGIN
    PACKAGE_ROL.DELETE_ROL(USEID);
    DELETE FROM USUARIO WHERE ID_USUARIO=USEID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No se encontró la categoría con ID para eliminar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    PROCEDURE GET_ROLES(UID IN NUMBER, DATOS OUT SYS_REFCURSOR)AS
    BEGIN
    OPEN DATOS FOR SELECT NOMBRE FROM ROL
    WHERE ID_USUARIO = UID;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera un tipo de dato diferente en los parámetros de entrada.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inesperado al abrir el cursor: ' || SQLERRM);
    END;

    PROCEDURE UPDATE_USUARIO (USERID IN NUMBER,USNAM IN VARCHAR2,CONTRAS IN VARCHAR2,NOMBR IN VARCHAR2,APELLI IN VARCHAR2,MAIL IN VARCHAR2,PHONE IN VARCHAR2,ACTV IN NUMBER) AS
    BEGIN
    UPDATE USUARIO SET USERNAME=USNAM, PASSWORD=CONTRAS,NOMBRE=NOMBR, APELLIDOS=APELLI,CORREO=MAIL, TELEFONO=PHONE,ESTADO=ACTV WHERE ID_USUARIO=USERID;
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar.');
    END IF;
    EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Se espera otro tipo de dato de entrada.');
    END;

    FUNCTION USUARIO_EXISTE (UNAME IN VARCHAR2, CORRE IN VARCHAR2) RETURN NUMBER
    IS
    BEGIN
        FOR DATOS IN (SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO FROM USUARIO) LOOP
            IF DATOS.USERNAME = UNAME OR DATOS.CORREO = CORRE THEN
                RETURN 1; -- TRUE
            END IF;
        END LOOP;
        RETURN 0; -- FALSE
    EXCEPTION
        WHEN VALUE_ERROR THEN
            DBMS_OUTPUT.PUT_LINE('Error: Datos de entrada no válidos.');
            RETURN -1;

        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Error: No se encontró la tabla o los datos.');
            RETURN -1;
    END;
END;

/
--------------------------------------------------------
--  DDL for Function USUARIO_EXISTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "ADMIN_LENGUAJES"."USUARIO_EXISTE" (UNAME IN VARCHAR2, CORRE IN VARCHAR2) RETURN NUMBER
IS
BEGIN
    FOR DATOS IN (SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDOS, CORREO, TELEFONO, ESTADO 
                  FROM USUARIO) LOOP
        IF DATOS.USERNAME = UNAME OR DATOS.CORREO = CORRE THEN
            RETURN 1; -- TRUE
        END IF;
    END LOOP;
    RETURN 0; -- FALSE
EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('Error: Datos de entrada no válidos.');
        RETURN -1;

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Error: No se encontró la tabla o los datos.');
        RETURN -1;
END;

/
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."CATEGORIA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CATEGORIA" MODIFY ("RUTA_IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CATEGORIA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CATEGORIA" ADD CONSTRAINT "CATE_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."CATEG_ID_IDX" ON "ADMIN_LENGUAJES"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUEGO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("IMAGEN" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("EXISTENCIAS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" ADD CONSTRAINT "JUEGO_PK" PRIMARY KEY ("ID_JUEGO")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."JUEGO_ID_IDX" ON "ADMIN_LENGUAJES"."JUEGO" ("ID_JUEGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."CONTACTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CONTACTO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CONTACTO" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CONTACTO" MODIFY ("MENSAJE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."CONTACTO" ADD CONSTRAINT "CONT_PK" PRIMARY KEY ("ID_CONTACTO")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."CONT_ID_IDX" ON "ADMIN_LENGUAJES"."CONTACTO" ("ID_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."ROL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."ROL_ID_IDX" ON "ADMIN_LENGUAJES"."ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("CORREO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" ADD CONSTRAINT "USU_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."USU_ID_IDX" ON "ADMIN_LENGUAJES"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."FACTURA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."FACTURA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."FACTURA" ADD CONSTRAINT "FACT_PK" PRIMARY KEY ("ID_FACTURA")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."FACT_ID_IDX" ON "ADMIN_LENGUAJES"."FACTURA" ("ID_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."ESTADO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."ESTADO" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."ESTADO" ADD CONSTRAINT "EST_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."EST_ID_IDX" ON "ADMIN_LENGUAJES"."ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
  ALTER TABLE "ADMIN_LENGUAJES"."ESTADO" ADD CONSTRAINT "U_ESTADO" UNIQUE ("ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" MODIFY ("ID_JUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" ADD CONSTRAINT "DETALLE_FACTURA_PK" PRIMARY KEY ("ID_DETALLE_FACTURA")
  USING INDEX (CREATE INDEX "ADMIN_LENGUAJES"."DETALLE_FACTURA_ID_IDX" ON "ADMIN_LENGUAJES"."DETALLE_FACTURA" ("ID_DETALLE_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO_LENGUAJES" )  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."CATEGORIA" ADD CONSTRAINT "FK_CATE" FOREIGN KEY ("ESTADO")
	  REFERENCES "ADMIN_LENGUAJES"."ESTADO" ("ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" ADD CONSTRAINT "DETALLE_FACTURA_FK1" FOREIGN KEY ("ID_FACTURA")
	  REFERENCES "ADMIN_LENGUAJES"."FACTURA" ("ID_FACTURA") ENABLE;
  ALTER TABLE "ADMIN_LENGUAJES"."DETALLE_FACTURA" ADD CONSTRAINT "DETALLE_FACTURA_FK2" FOREIGN KEY ("ID_JUEGO")
	  REFERENCES "ADMIN_LENGUAJES"."JUEGO" ("ID_JUEGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."FACTURA" ADD CONSTRAINT "FACT_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN_LENGUAJES"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUEGO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" ADD CONSTRAINT "JUEGO_FK" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "ADMIN_LENGUAJES"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "ADMIN_LENGUAJES"."JUEGO" ADD CONSTRAINT "FK_JUEGO" FOREIGN KEY ("ESTADO")
	  REFERENCES "ADMIN_LENGUAJES"."ESTADO" ("ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."ROL" ADD CONSTRAINT "ROL_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN_LENGUAJES"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "ADMIN_LENGUAJES"."USUARIO" ADD CONSTRAINT "FK_USER" FOREIGN KEY ("ESTADO")
	  REFERENCES "ADMIN_LENGUAJES"."ESTADO" ("ESTADO") ENABLE;
